DELETE FROM VITALS_LOGS
WHERE Admission_ID IN (
    SELECT a.Admission_ID 
    FROM ADMISSIONS a
    WHERE a.Dept_ID = 14
);

DELETE FROM PRESCRIPTIONS
WHERE Medication_ID IN (SELECT Medication_ID FROM MEDICATIONS WHERE Med_Name LIKE 'Med_1%')
AND Admission_ID IN (SELECT Admission_ID FROM ADMISSIONS WHERE Dept_ID = 14);

DELETE FROM TEST_RESULTS
WHERE Admission_ID NOT IN (
    SELECT DISTINCT Admission_ID 
    FROM VITALS_LOGS
);