SELECT * FROM PRESCRIPTIONS;
SELECT * FROM MEDICATIONS;
SELECT * FROM VITALS_LOGS;
SELECT * FROM ADMISSIONS;
SELECT * FROM ROOMS;
SELECT * FROM DEPARTMENTS;
SELECT * FROM DOCTORS;
SELECT * FROM PATIENTS;