-- הדגמת ROLLBACK:
BEGIN; 

SELECT COUNT(*) FROM VITALS_LOGS;

DELETE FROM VITALS_LOGS WHERE Log_ID = (SELECT Log_ID FROM VITALS_LOGS LIMIT 1);

SELECT COUNT(*) FROM VITALS_LOGS;

ROLLBACK;
SELECT COUNT(*) FROM VITALS_LOGS;

-- הדגמת COMMIT:     
BEGIN; 
UPDATE DEPARTMENTS SET Floor = 8 WHERE Dept_ID = 14;

SELECT Dept_Name, Floor FROM DEPARTMENTS WHERE Dept_ID = 14;

COMMIT;

SELECT Dept_Name, Floor FROM DEPARTMENTS WHERE Dept_ID = 14;